project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('accounts.urls')),
    path('rental/', include('rental.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rental/urls.py
from django.urls import path

from rental import views

app_name = 'rental'

urlpatterns = [
    path('', views.index, name="index"),
    # path('loginVerify/', views.loginVerify, name='loginVerify'),
    path('viewCar/', views.viewCar, name='viewCar'),
    path('bookCar/', views.bookCar, name='book-car'),
    #path('<int:pk>/', views.ViewCar.as_view(), name='viewCar'),
]

rental/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
# Create your models here.


class Car(models.Model):
    carName = models.CharField(max_length=30)
    priceDay = models.FloatField()
    priceWeek = models.FloatField()
    numSeats = models.IntegerField()
    numDoors = models.IntegerField()
    # brand = models.CharField(max_length=20)
    # model = models.CharField(max_length=20)
    gear = models.CharField(max_length=9)

    def __str__(self):
        return self.carName


class Booking(models.Model):
    carID = models.ForeignKey(Car, on_delete=models.CASCADE)
    startDate = models.DateField()
    endDate = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Booking #" + self.bookingID


class UserType(models.Model):
    userType = models.IntegerField()
    typeDesc = models.CharField(max_length=5)



# class User(models.Model):
#     username = models.CharField(max_length=30)
#     password = models.CharField(max_length=30)
#     firstName = models.CharField(max_length=20)
#     lastName = models.CharField(max_length=30)
#     email = models.CharField(max_length=30)
#     phoneNumber = models.CharField(max_length=10)
#     usertype = models.ForeignKey(UserType, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.firstName + " " + self.lastName

rental/views.py
import dateutil.parser

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
# Create your views here.
from rental.models import Booking, Car
from accounts.models import Profile

from dateutil.parser import parse


@login_required
def index(request):
    cars = Car.objects.all()
    context = {'list':cars}

    return render(request, "rental/index.html", context)

def viewCar(request):
    try:
        for k, v in request.GET.items():
            if k != "csrfmiddlewaretoken":
                car_id = k
        car = Car.objects.get(id=car_id)
        context = {'car': car}
    except Car.DoesNotExist:
        raise Http404("Car not found")
    return render(request, "rental/viewCar.html", context)

def bookCar(request):
    if request.method == "POST":
        carId = request.POST['carId']
        carObj = Car.objects.get(id=carId)
        
        startDate = request.POST['start-date']
        endDate = request.POST['end-date']



        if startDate == "" or endDate == "":
            context = {'car':carObj, 'message':'Please fill in the blanks!', 'state':0}
            return render(request, 'rental/viewCar.html', context)
        elif parse(startDate) > parse(endDate):
            context = {'car':carObj, 'message':'Start Date must be smaller than End Date!', 'state':0}
            return render(request, 'rental/viewCar.html', context)
            
        booking = Booking.objects.filter(carID = carObj).order_by('-startDate').first()
        if booking is not None:
            prevEndDate = booking.endDate
            if prevEndDate >= dateutil.parser.parse(startDate).date():
                context = {'car':carObj, 'message':'Failure! This car has been already booked.', 'state':0}
            else:
                booking = Booking()
                booking.carID = carObj
                booking.startDate = startDate
                booking.endDate = endDate
                booking.user = User.objects.get(id=request.user.id)
                booking.save()
                context = {'car':carObj, 'message':'Success! You have booked this car.', 'state':1}

        else:
            booking = Booking()
            booking.carID = carObj
            booking.startDate = startDate
            booking.endDate = endDate
            booking.user = User.objects.get(id=request.user.id)
            booking.save()

            context = {'car':carObj, 'message':'Success! You have booked this car.', 'state':1}

        return render(request, 'rental/viewCar.html', context)

rental/templates/rental/_footer.html
{% load static %}
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                Copyright© 2020 by Jackie
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-md-block">
                    <a href="javascript: void(0);">Buy Now</a>
                    <a href="#">Rate us</a>
                    <a href="#">Support</a>
                </div>
            </div>
        </div>
    </div>
</footer>

rental/templates/rental/_topbar.html
{% load static %}
<div class="navbar-custom">
    <!------------------------------------->
    <!-- right side topbar content start -->
    <ul class="list-unstyled topbar-right-menu float-right mb-0">

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user arrow-none mx-0" data-toggle="dropdown" href="#"
               role="button" aria-haspopup="false" aria-expanded="false">
                <span class="account-user-avatar">
                    <img src="{% static 'images/users/avatar-1.jpg' %}" alt="user-image"
                         class="rounded-circle">
                </span>
                <span>
                    <span class="account-user-name">{{ user.username }}</span>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                <a href="{% url 'logout' %}" class="dropdown-item"><i class="feather icon-power text-danger"></i>
                    &nbsp; Log Out</a>
            </div>
        </li>
    </ul>
    <!-- right side topbar content end -->
    <!------------------------------------->

    <!---------------------------------------------->
    <!-- Left side topbar content Start -->


    <div class="header-search">
        <span class="account-user-avatar" >
            <a href="{% url 'rental:index' %}"><img src="{% static 'images/logo-dark.png' %}" alt="user-image"></a>
        </span>
    </div>
    <!-- Left side topbar content end -->
    
</div>

rental/templates/rental/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8"/>
    <title>Car Rental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Beethemesdesign" name="author"/>

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">


    <!-- third party css -->
    <link href="{% static 'css/vendor/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css"/>
    <!-- third party css end -->

    <!-- Required css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" type="text/css"/>
    {% block style %}
    {% endblock %}

</head>

<body>

<!-- Begin page -->
<div class="wrapper">

    <!-- ============================================================= -->
    <!-- ===============    side menu content start  ================= -->
    <!-- ============================================================= -->
    <!-- ============================================================= -->
    <!-- ===============     side menu content End   ================= -->
    <!-- ============================================================= -->


    <!-- ============================================================== -->
    <!-- Start Page Content here -->
    <!-- ============================================================== -->

    <div class="" style="overflow: hidden;padding: 5px 20px;min-height: 80vh;">
        <div class="content">

            <!-- ============================================================= -->
            <!-- ===============    Top bar header content start  ================= -->
            <!-- ============================================================= -->
            {% include 'rental/_topbar.html' %}
            <!-- ================================================================== -->
            <!-- ===============    Top bar header content end  ================= -->
            <!-- ================================================================== -->

            {% block content_header %}
            {% endblock %}
            <!-- Start Content-->
            {% block content %}
            {% endblock %}

        </div>
    </div>
    <!-- container -->
    <!-- content -->
    <div>
        <!-- ============================================================= -->
        <!-- ===============    footer content start  ================= -->
        <!-- ============================================================= -->


        <!-- ============================================================= -->
        <!-- ===============    footer content start  ================= -->
        <!-- ============================================================= -->


    </div>

    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->


</div>
<!-- END wrapper -->

{% block script %}
    <!-- Required js -->
    <script src="{% static 'js/app.js' %}"></script>

    <!-- third party js -->
    <script src="{% static 'js/vendor/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-jvectormap-world-mill-en.js' %}"></script>
    <!-- third party js ends -->

    <!-- third party:js -->
    <script src="{% static 'js/vendor/apexcharts.min.js' %}"></script>

    <!-- demo app -->
{#    <script src="{% static 'js/demo/demo.dashboard.js' %}"></script>#}
    <!-- end demo js-->
{% endblock %}
{% block extra_script %}
{% endblock %}
</body>

</html>

rental/templates/rental/index.html
{% extends './base.html' %}
{% load static %}


{% block content %}
<h1>Rent a Car</h1>
<div class="d-flex flex-wrap">

    
    
    {%  for c in list %}
    <div class="border ml-2 mb-2 p-2">
        <form method="get" action="{%  url 'rental:viewCar' %}">
            {% csrf_token %}
                <p style="font-size:130%;font-family:verdana"> {{ c.carName }} <br/></p>
                <ul>
                <li style="font-family:verdana;">Doors: {{ c.numDoors }}</li>
                <li style="font-family:verdana;">Seats: {{ c.numSeats }}</li>
                <li style="font-family:verdana;">Transmission: {{ c.gear }}</li>
                <li style="font-family:verdana;">Price/Day: {{ c.priceDay }} AED</li>
                <li style="font-family:verdana;">Price/Week: {{ c.priceWeek }} AED</li>
                </ul>
                <div class="text-center">
                    <button class="btn btn-primary text-center" type="submit" value="Book Car" name="{{ c.id }}" id="id">Book Car</button>
                </div>
            </form>
    </div>
    {% endfor %}
</div>

{% endblock %}

rental/templates/rental/viewCar.html
{% extends './base.html' %}
{% load static %}


{% block content %}
<div class="d-flex pt-5 justify-content-center w-100">
    <div class="w-50">
        {%if message %}
        {% if state == 0 %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        {% else %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endif %}
    </div>

</div>
<div class="d-flex align-items-center justify-content-center pt-5">
    <div>
        <p style="font-size:130%;font-family:verdana"> {{ car.carName }} <br /></p>
        <ul>
            <li style="font-family:verdana;">Doors: {{ car.numDoors }}</li>
            <li style="font-family:verdana;">Seats: {{ car.numSeats }}</li>
            <li style="font-family:verdana;">Transmission: {{ car.gear }}</li>
            <li style="font-family:verdana;">Price/Day: {{ car.priceDay }} AED</li>
            <li style="font-family:verdana;">Price/Week: {{ car.priceWeek }} AED</li>
        </ul>
        <br /><br />
        <form method="POST" class="d-flex flex-wrap flex-column" action="{%  url 'rental:book-car' %}">
            {% csrf_token %}
            <input type='hidden' id='car-id' value={{car.id}} name="carId" />
            <label for="start">Start date:</label>
            <input type="date" id="start" name="start-date" value="2021-01-01" min="2021-01-01" max="2030-12-31">
            <label for="end">End date:</label>
            <input type="date" id="end" name="end-date" value="2021-01-01" min="2021-01-01" max="2030-12-31">
            <button class="btn btn-primary mt-4" type="submit" value="Book Car" name="{{ c.id }}" id="id">Book
                Car</button>
        </form>
    </div>
</div>

{% endblock %}